############################
# Configuration Version.
# Shouldn't be changed unless you know what you're doing
############################
version: 1.0

###############################################################################
###                                                                         ###
###                       Directory Listing                                 ###
###                                                                         ###
###############################################################################

#####################################
# Quest directory. All .yml files
# in the directory are loaded as
# quest templates
#####################################
questDir: quests/

#####################################
# Save directory. A folder where
# QM will save and load quest state
# information between starts and stops
#####################################
saveDir: savedata/

#####################################
# Region directory. All .yml files
# found are loaded as region files.
# These define enemy spawns, regions
#####################################
regionDir: region/

#####################################
# Spell directory. All .yml files
# found are loaded as spell files.
# These define spells available
# and their effects/costs/etc
#####################################
spellDir: spells/

#####################################
# Skill directory. Skills look here
# to find and/or create their specific
# configuration files
#####################################
skillDir: skills/


###############################################################################
###                                                                         ###
###                          Manager Settings                               ###
###                                                                         ###
###############################################################################

#####################################
# Which worlds should be treated as
# quest worlds? Players not in these
# worlds are overlooked by QM
#####################################
questWorlds:
  - "QuestWorld"
  - "QuestTutorial"
  
#####################################
# Quest templates can be cleaned up if
# they aren't able to be loaded in.
# This turns that off
#####################################
config:
  conservativeMode: true
  
#####################################
# Some plugins modify the way chunks
# are loaded or prevent certain ones
# from unloaded at all. This can cause
# issues with villagers. This option
# removes villagers when chunks are
# unloaded and puts them back when
# needed. Comes with a little overhead
# but fixes potential NPC clones
#####################################
world:
  villagerCleanup: true


###############################################################################
###                                                                         ###
###                          Player Interfaces                              ###
###                                                                         ###
###############################################################################

#####################################
# Should menus tell you when they
# have expired, but you try clicking
# them again? Turn on to discourage
# spammy clickers
#####################################
menus:
  verboseMenus: false
  
#####################################
# Player-specific options. Only apply
# when a player is in a QuestWorld
#####################################
player:
  #####################################
  # Can a player craft (crafting table
  # or regular inventory crafting)
  #####################################
  allowCrafting: false

  #####################################
  # Can players tame animals in QWorlds?
  #####################################
  allowTaming: false
  
  #####################################
  # Whether players can rename items
  # on anvils. Important if items and
  # drops rely on item names for info
  #####################################
  allowNaming: false;
  
  #####################################
  # Maximum players that can be in a party
  #####################################
  maxPartySize: 4
  
#####################################
# QuestWorld interfacing options
#####################################
interface:
  #####################################
  # Should QM use MultiverPortals to
  # set player checkpoints when taking
  # a portal to and from a QuestWorld?
  # REQUIRES MultiverPortals
  #####################################
  usePortals: true
  
  #####################################
  # XP can be used as money; When XP
  # is picked up, it'll be used as xp
  # instead, and the player's experience
  # level is used as money indicator
  #####################################
  useXPMoney: true
  
  #####################################
  # QM can change the amount of xp
  # dropped by mobs automatically based
  # on their name. This only works on
  # mobs with names that include their
  # 'level' []in format Mob (Lvl 4)]
  #####################################
  adjustXP: true
  
  #####################################
  # Should player titles prefix their
  # chat messages? Works across worlds
  #####################################
  titleInChat: true
  
  #####################################
  # The Magic Compass points players to
  # select locatable objectives for quests
  # This configures the compass
  #####################################
  compass:
    #####################################
    # Should compasses work like the magic
    # compass? If false, compasses function
    # the same as vanilla compasses
    #####################################
    enabled: true
    
    #####################################
    # What object should be used as a
    # compass? This is a Bukkit.Material
    #####################################
    type: "COMPASS"
    
    #####################################
    # What name should compasses have to
    # have to be considered valid magic
    # compasses?
    #####################################
    name: "Magic Compass"
    
  #####################################
  # Magic interfaces. Don't mean anything
  # if magic is disabled below
  #####################################
  magic:
    #####################################
    # Name vessels are required to have to
    # be considered real and valid
    #####################################
    holderName: "Spell Vessel"
    
    #####################################
    # What block do players use their
    # vessels on to assign it a new spell?
    # This is a Bukkit.Material
    #####################################
    alterBlockType: "ENCHANTMENT_TABLE"
    
  #####################################
  # Spell Weaving interfaces
  #####################################
  spellweaving:
    #####################################
    # Name invokers are required to have
    # to  be considered valid
    #####################################
    invokerName: "Spell Invoker"
    
    #####################################
    # Item used as the invoker. Works well
    # when you haven't made an invocation
    # spell and want to use an item instead
    # This is a Bukkit.Material
    #####################################
    invokerType: CARROT_STICK
    
  #####################################
  # Mark/Recall Interfaces
  #####################################
  recall:
    #####################################
    # Name recallers are required to have
    # to  be considered valid
    #####################################
    recallerName: "Waystone"
    
    #####################################
    # Item used as the recaller. Works well
    # when you haven't made a recall
    # spell and want to use an item instead
    # This is a Bukkit.Material
    #####################################
    recallerType: BOOK
    
    #####################################
    # Item used as mark anchors. Works well
    # when you haven't made a mark
    # spell and want to use an item instead
    # This is a Bukkit.Material
    #####################################
    markerType: BEACON
    
    #####################################
    # QM can erase marks right after a
    # recall to discourage 'home base'
    # thinking. Should it?
    #####################################
    singleRecall: false
    
    #####################################
    # How much mana should a recall with
    # the recaller cost? Follows the same
    # rules as mana regen: 100 is 100 mana.
    # -100 is 100% mana
    #####################################
    cost: -100
  
  
###############################################################################
###                                                                         ###
###                          Feature Settings                               ###
###                                                                         ###
###############################################################################  
  
#####################################
# Default Skill behavioral settings
#####################################
skill:
  #####################################
  # Maximum skill level for any skill
  #####################################
  cap: 100
  growth:
    #####################################
    # Percent tnl given when a skill is
    # successfully used with an action of
    # the same level
    #####################################
    success: 0.10
    
    #####################################
    # Percent tnl given when a skill is
    # failed, but the level matched. Can
    # be 0.0 and everything works fine
    #####################################
    fail: 0.025
    
    #####################################
    # Maximum difference between skill
    # level and action level where a player
    # still gets xp
    #####################################
    cutoff: 10
    
    #####################################
    # How much higher a skill can be and
    # the player still get xp for a failure
    #####################################
    cutoffUpper: 10
    
#####################################
# Magic system configuration
#####################################
magic:
  #####################################
  # Can magic be used?
  #####################################
  enabled: true
  
  #####################################
  # How much mana do new players get
  #####################################
  startingMana: 20
  
  #####################################
  # How much mana is regenned in the day?
  # If positive, this is the amount.
  # if negtive, this is the percent
  # (-50 is 50% of the total is regenned)
  #####################################
  dayRegen: 1.0
  
  #####################################
  # How much mana is regenned in the day?
  # If positive, this is the amount.
  # if negtive, this is the percent
  # (-50 is 50% of the total is regenned
  #####################################
  nightRegen: 1.0
  
  #####################################
  # Do players ONLY regen if they can
  # see the sky?
  #####################################
  outsideRegen: true
  
  #####################################
  # How much mana does a player get each
  # time they kill something?
  # If positive, this is the amount.
  # if negtive, this is the percent
  # (-50 is 50% of the total is regenned
  #####################################
  regenOnKill: 1.0
  
  #####################################
  # How much mana does a player get when
  # they absorb a piece of xp
  # If positive, this is the amount.
  # if negtive, this is the percent
  # (-50 is 50% of the total is regenned
  #####################################
  regenOnXP: 1.0
  
  #####################################
  # How much mana does a player get for
  # each piece of food they eat
  # If positive, this is the amount.
  # if negtive, this is the percent
  # (-50 is 50% of the total is regenned
  #####################################
  regenOnFood: -50.0
  
#####################################
# Maximum summons a player can have
# at a time
#####################################
summonLimit: 2

#####################################
# Spell Weaving settings
#####################################
spellweaving:
  enabled: true
  #####################################
  # Should the invoker work? If not but
  # you want to use spellweaving, you'll
  # need to make sure to create a spell
  # that has the Invoke Effect
  #####################################
  useInvoker: true