############################
# Configuration Version.
# Shouldn't be changed unless you know what you're doing
############################
version: 1.0

############################
# List of quests 
############################
quests:
  - "Know Your Enemy"
  - "The Fletcher"
  - "Upgrades"
  - "Mana"
  - "Drowned Sorrows"
  - "Among The Wreckage"
  - "Slimey Things"
  - "Strange Creatures"
  - "Plain And Simple 2"
  - "No Time"
  - "Sun Vermin"
  - "Wandering Curiosity"
  - "Deep Blue"
  - "Tuxedo"
  - "Unnatural"
  - "Sea Enemies"
  - "Restless Imps"
  - "Imp Safety"
  - "Imp Hardware"
  - "Dancing Bones"
  - "Not Far Enough"
  - "Too Many Legs"
  - "Dazling Spiders"
  - "Water Logged"
  - "Natural Cleansing"
  - "Twin Dragons"
  - "Sticky Wishes"
  - "The Imbuer"
  - "Quest for the Apples"
  - "Slippery Dreams"
  - "Frozen With Fear"
  - "Spider Hunting"
  - "Managing The Realm"
  - "Getting Started"
  - "A Whole New World"
  - "The Right Side"
  - "More Than Bats"
  - "Fire Maze"
  - "Soft Like Me"
  - "Bad Dog"
  - "Out At Onuit"
  - "Down In A Hole"
  - "Moonlit Hunting"
  - "White Petals"
  - "Mite As Well"
  - "Stealing Hearts"
  - "A Hellish Discovery"
  - "Dreadful News"
  - "Clean Sweep"
  - "Tastes Like Crab"
  - "Food For Death"
  - "Better Than The Dead"
  - "Besting The Night"
  - "First Orders"
  - "Beating Strong"
  - "Better Than Aloe"
  - "Savages"
  - "Deep Gaze"
  - "Dark Depths"
  - "Toxic Fashion"
  - "Relatives"
  - "Relatively Difficult"
  - "World Tour"
  - "Darker Places"
  - "Not Peerless"
  - "Packing Heat"
  - "Heat Waves"
  - "Into The Oven"
  - "Leading The Pack"
  - "Down At The Lake"
  - "Around The Corner"
  - "Curious Undead"
  - "Rotten Breath"
  - "The Walking Dead"
  - "Shadow Chaser"
  - "Just Bones"
  - "Hell Spawn"
  - "Hilt Of The Warrior"
  - "Forging Bonds"
  - "Support Relations"
  - "Weapon Crafting"
  - "Free Lunch"
  - "Nighttime Meeting"
  - "Neighbors"
  - "Playing Fetch"
  - "Artifacts"
  - "The Moon Route"
  - "The Sisters"
  - "King Slime"
  - "Piecing It Together"
  - "Pup Slaying"
  - "Basement Treasure"
  - "Ancient Treasure"
  - "Guiding Hands"
  - "A Steady Hand"
  - "Treasure At Last"
  - "Probably Fine"
  - "Monster Hunter"
  - "Searching for Peace"
  - "Unmarried Nations"
  - "Sponsoring Death"
  - "Proof"
  - "A Hero of Heroes"
  - "Help Wanted"
  - "Research"
  - "In Preparation"
  - "Ancient Knowledge"
  - "Wasted Time"
  - "Admist The Coal"
  - "Earning Trust"
  - "Differences"
  - "Rebury"
  - "True Beauty"
  - "Forest Hunting"
  - "Bandit Raid"
  - "Simple Service"
  - "Forge Apprentice"
  - "Strong Spirit"
  - "Crafting Ties"
  - "Rival Forges"
  - "Wolves"
  - "Lost Toy"
  - "Angst"
  - "Plain And Simple"
  - "Inheritance"
  - "Interlibrary Loan"
  - "Hired Hand"
  - "Off The Books"
  - "Fossils"
  - "The Gray"
  - "Understudy"
  - "Lungs of Steal"
  - "Young Blood"
  - "Excuses"
  - "Pursuit"
  - "Release"
  - "Arachnidemons"
  - "Forest Dweller"
  - "Noisy Neighbors"
  - "Reagents"
  - "Momentos"
  - "Family History"
  - "Twisted Memories"
  - "Family Secrets"
  - "Imp Route"
  - "Blessed Knowledge"
  - "Darkest Black"
  - "Void Master"
  - "Water Master"
  - "Light Master"
  - "Curiosity"
  - "Might of Generations"
questDir: quests/
saveDir: savedata/
enemyDir: enemies/
spellDir: spells/
skillDir: skills/
skill:
  cap: 100
  growth:
    success: 0.10
    fail: 0.025
    cutoff: 10
    cutoffUpper: true
menus:
  verboseMenus: false
config:
  conservativeMode: true
player:
  allowCrafting: false
  allowTaming: false
  allowNaming: false;
  maxPartySize: 4
world:
  villagerCleanup: true
interface:
  usePortals: true
  useXPMoney: true
  adjustXP: true
  titleInChat: true
  compass:
    enabled: true
    type: "COMPASS"
    name: "Magic Compass"
  magic:
    holderName: "Spell Vessel"
    alterBlockType: "ENCHANTMENT_TABLE"
  spellweaving:
    invokerName: "Spell Invoker"
    invokerType: CARROT_STICK
  crafting:
    combineQuality: true
questWorlds:
  - "QuestWorld"
  - "QuestTutorial"
summonLimit: 2
spellweaving:
  enabled: true
  useInvoker: true
magic:
  enabled: true
  startingMana: 20
  dayRegen: 1.0
  nightRegen: 1.0
  outsideRegen: true
  regenOnKill: 1.0
  regenOnXP: 1.0
  regenOnFood: -50.0